### ISSUE TITLE
Can I write JS/TS/(S)CSS + HBS demos in demos folders instead of markdown?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#100]
Reason being is that VSCode and WebStorm doen't have support for intellisense in embedded languages in markdown.
(which is funny because in (neo)vim, I have everything :upside_down_face: ).

For (non-vim) authors who need to make demos that are heavily dependent on complex structures, having TS intellisense in demos would be a huge win.

I imagine these'd work just like components? but in the `docs/**/demos` directories?

**Comment by josemarluedke** [comment]
You could set up code-import instead of inlining the content in markdown.

https://github.com/kevin940726/remark-code-import

This way you can have all your demo components in a plain file.


(Interesting you can get intellisense in code blocks in neovim, I need to look at your nvim setup. :D)

**Comment by NullVoxPopuli** [comment]
Maybe instead, is possible to write a docfy plugin to move demo files to the app component folder?

Cause then I'd probably do regular js imports in the markdown and skip all the remark awkwardness for authors
