### ISSUE TITLE
Is there a way to support other languages like asciidoc ?

### ISSUE THREAD

**Issue by ncoquelet** [josemarluedke/docfy#50]
Hi,
This project seems realy awesome.
I want to write UI documentation on our project for long time and docfy will simplify this task for sure.
But instead markdown, we already use asciidoc which we prefer the syntax and it's more adapt to technical documentation.

Is the core module of docfy can be easily extended to add support to asciidoc (via asciidoctor) or it is too coupled with remark for moment ?

Thanks a lot for this project.

**Comment by josemarluedke** [comment]
@ncoquelet Thank you for checking Docfy out. Unfortunately, Docfy was designed to be used with markdowns and remark. 

If you do decide to use markdown instead, you could convert your existing files to markdown and use Docfy: https://gist.github.com/cheungnj/38becf045654119f96c87db829f1be8e

Thanks again for checking Docfy out.

**Comment by ncoquelet** [comment]
Thank you for your response.
You can imagine that we don't change our markup to use a new tool.
After read your code, it seems that it could be a not too much effort to add more generic on the markup support. 
When I have some time, I will try some stuff to add asciidoc support.
Also, if you don't known it, I recommend you to take a quick look at asciidoc https://asciidoctor.org/docs/asciidoc-vs-markdown/
