### ISSUE TITLE
[Ember] Add support for rootURL

### ISSUE THREAD

**Issue by josemarluedke** [josemarluedke/docfy#55]
For the Ember Apps, we should support rootURL as that is a common use case when deploying to GitHub Pages.

![image](https://user-images.githubusercontent.com/230476/96525923-19c57300-1231-11eb-8df0-b1818273e5fb.png)

It seems to be able to use `recognize` from the Ember Router Service, we must pass the rootURL as well.

**Comment by josemarluedke** [comment]
cc/ @knownasilya.

**Comment by NullVoxPopuli** [comment]
for others coming across this, prepending the rootURL to every link is sufficient, as the error says

**Comment by josemarluedke** [comment]
It should be straightforward to fix the DocfyLink component. 

We just need to load the app config and use the Root URL here:

https://github.com/josemarluedke/docfy/blob/master/packages/%40docfy/ember/addon/components/docfy-link.ts#L16

**Comment by knownasilya** [comment]
Nice

**Comment by josemarluedke** [comment]
Note for these using rootURL, if you have assets in your markdown, like images, you will need to set `staticAssetsPath` accordingly: https://docfy.dev/docs/configuration#staticassetspath
