### ISSUE TITLE
Images referenced in markdown do not get their fingerprinted URL stubbed in during build

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#62]
for example, if I do:
```md
![alt text](/nullvoxpopuli.png)
```

I'd expect that during a production build, the output would be the equiv of:

```md
![alt text]($ASSET_URL_ROOT/nullvoxpopuli-abcdef1234thehash.png)
```

but what happens instead: 

```md
![alt text](/nullvoxpopuli.png)
```

**Comment by NullVoxPopuli** [comment]
turns out this is partially my fault (go figure).

my image is _actually_ a jpeg, which isn't included in the `broccoli-asset-rev` defaults (`jpg` is tho). So, either adding `jpeg` to the build config, or renaming the to `jpeg` solves the issue with local production. gonna test deployment with the prefix URL and see if it works the same

**Comment by josemarluedke** [comment]
Thanks for letting me know. Closing this, for now, let me know if you find any other issue.

**Comment by NullVoxPopuli** [comment]
Looks like the url prefix is fine too. But the rootUrl is prepeneded twice for some reason

**Comment by NullVoxPopuli** [comment]
ok, I've confirmed this is actually an issue with our deploy setup. We're good! :D
