### ISSUE TITLE
Inline components in markdown?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#64]
I have this:

```md
# Header

some text
<Link @href="a url">click me</Link>
more text
```

but I'm getting the error: 
```
Closing tag `Link` (on line 3) did not match last open tag `p` (on line 2).
```

Is this only sometimes supported? 
It'd be great if we could arbitrarily invoke components anywhere while authoring markdown

**Comment by josemarluedke** [comment]
Invoking Ember Components are supported in the Ember stack, using [remark-hbs](https://github.com/josemarluedke/remark-hbs). Not sure why this case exactly doesn't work, but if you add empty lines between the text, it will work.


```md
# Header

some text

<Link @href="a url">click me</Link>

more text
```

**Comment by josemarluedke** [comment]
I will close this as it isn't an issue with Docfy. Feel free to open a new issue in remark-hbs.
