### ISSUE TITLE
How do you augment the markdown output to have classes applied?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#69]
This'd be handy for tailwindcss folks as well. Rather than having a cascading stylesheet which can interfere with demos, we could have the markdown output include some classes that match to our tailwind config?

**Comment by josemarluedke** [comment]
You should take a look at remark plugins for this. You can walk the AST and apply classes when necessary.

For tailwind specifically, you can take a look at how I did in Frontile: https://github.com/josemarluedke/frontile/blob/master/site/.docfy-config.js#L6-L43

**Comment by josemarluedke** [comment]
Closing this. Let me know if you still have questions about it.

**Comment by NullVoxPopuli** [comment]
thanks! this was helpful. Instead of using the prose classes, I'm adding individual classes for each of the main markdown elements -- prose has cascading, afaict, and for interweaving demos and prose, I didn't want any CSS cascading at all :)
