### ISSUE TITLE
Invalid "Writing Markdown - Demos" link in docs

### ISSUE THREAD

**Issue by MichalBryxi** [josemarluedke/docfy#78]
Page: https://docfy.dev/docs/ember/writing-demos/
Link: "Writing Markdown - Demos."
Goes to: https://docfy.dev/docs/writing-markdown.md#demos
Which renders:

![Screenshot 2021-03-05 at 18 32 12](https://user-images.githubusercontent.com/847473/110158316-1e09bb80-7de1-11eb-87e4-d5a84ff35491.png)

**Comment by josemarluedke** [comment]
@MichalBryxi Thank you for letting me know. I need to setup markdown linting to catch these things. This bug was introduced in #72.
