### ISSUE TITLE
Docfy Plugins: file path to file in meta

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#79]
I would like to iterate over detected README.md files in a monorepo and swap out their `title` with the `name` value from their `package.json` to do that, I need to know where the `README.md` is located (so I can check if there is a sibling `package.json` file

**Comment by josemarluedke** [comment]
You can write a plugin to do this without needing to set the file path in the metadata. But in case you do want to have this available in the meta, here is a quick plugin that adds that info to meta.

```js
const path = require('path');
const plugin = require('@docfy/core/lib/plugin');

const myPlugin = plugin({
  runAfter(ctx) {
    ctx.pages.forEach((page) => {
      page.meta.pluginData['source'] = path.join(
        page.sourceConfig.root,
        page.source
      );
    });
  }
});
```
