### ISSUE TITLE
Duplicated preview-template

### ISSUE THREAD

**Issue by ctjhoa** [josemarluedke/docfy#88]
If `@docfy/ember`  is installed as `dependencies` and **not** as `devDependencies` the markdown code snippet flagged `preview-template` are duplicated.

![2021-04-11-204930_418x382_scrot](https://user-images.githubusercontent.com/1716173/114321100-8ba7b680-9b08-11eb-849e-02c98aee8116.png)

Here is the freshly created ember-addon used for the screenshot with :
https://github.com/ctjhoa/test-docfy

I need `@docfy/ember` as dependency because I want to write an addon which is an abstraction for basic documentation components for my company.

**Comment by ctjhoa** [comment]
I suppose the issue is here
https://github.com/josemarluedke/docfy/blob/master/packages/ember/src/index.ts#L150

**Comment by josemarluedke** [comment]
Thanks for reporting this issue. This happens because of the nested addon. I have added a PR with guards against not running docfy in the parent addon, but rather in the host app.

**Comment by josemarluedke** [comment]
Published v0.4.3 with the fix for this.
