### ISSUE TITLE
Examples - combined into a tabbed UI?

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/docfy#96]
if I have a lot of examples, I'd like them  to be in some tabbed ui, rather than rendered all at the same time.
Is this possible?

**Comment by josemarluedke** [comment]
You probably will need a Docfy Plugin for this, it should overwrite the default plugin in Ember to support this. Alternatively, you could also overwrite the DocfyDemo component to add an expansion or something like that. But would not be tabbed.
